### ISSUE TITLE
Pydantic version 2 problems

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/jasen#166]
When upgrading to version two of pydantic (used by prp) the following error occurs:
```
Traceback (most recent call last):
  File "/data/bnf/sw/miniconda3/envs/jasen/bin/prp", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/prp/cli.py", line 121, in create_output
    res: QcMethodIndex = parse_quast_results(quast)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/prp/parse/qc.py", line 37, in parse_quast_results
    return QcMethodIndex(software=QcSoftware.QUAST, result=qc_res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bnf/sw/miniconda3/envs/jasen/lib/python3.11/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for QcMethodIndex
version
  Field required [type=missing, input_value={'software': <QcSoftware.... duplication_ratio=1.0)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing
```

**Comment by ryanjameskennedy** [comment]
This issue has been resolved by [prp](https://github.com/Clinical-Genomics-Lund/bonsai-prp)
