### ISSUE TITLE
No package metadata was found for prp

### ISSUE THREAD

**Issue by Emkago** [genomic-medicine-sweden/jasen#195]
Got an error while running a test run with provided S. aureus test samples (running locally on CentOS 7). When searching for solution online, I saw that the same problem appeared also for other tools, but I don't know how to solve it.

```
[kast31@vs478 JASEN]$ nextflow run main.nf -profile staphylococcus_aureus -config configs/nextflow.umea.config --csv assets/test_data/samplelist.csv
N E X T F L O W  ~  version 23.04.4
Launching `main.nf` [furious_allen] DSL2 - revision: 0f4c6e2b59
executor >  local (21)
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:assembly_trim_clean                    -
[68/3d8766] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:save_analysis_metadata (furious_allen) [100%] 1 of 1 ✔
[ae/6f513b] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (p1000)                          [100%] 1 of 1 ✔
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:spades_illumina                        -
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:spades_iontorrent                      -
[53/542a90] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:quast (p1000)                          [100%] 1 of 1 ✔
[87/f44b55] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:bwa_mem_ref (p1000)                    [100%] 1 of 1 ✔
[82/6a2913] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:samtools_index_ref (p1000)             [100%] 1 of 1 ✔
[af/e7cd30] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:post_align_qc (p1000)                  [100%] 1 of 1 ✔
[51/4e25c5] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:sourmash (p1000)                       [100%] 1 of 1 ✔
[b7/ccd15f] process > CALL_STAPHYLOCOCCUS_AUREUS:bwa_index (p1000)                                          [100%] 1 of 1 ✔
[11/e55e86] process > CALL_STAPHYLOCOCCUS_AUREUS:bwa_mem_dedup (p1000)                                      [100%] 1 of 1 ✔
[b6/7aa4b9] process > CALL_STAPHYLOCOCCUS_AUREUS:samtools_index_assembly (p1000)                            [100%] 1 of 1 ✔
[0e/a724ec] process > CALL_STAPHYLOCOCCUS_AUREUS:freebayes (p1000)                                          [100%] 1 of 1 ✔
[6f/62611d] process > CALL_STAPHYLOCOCCUS_AUREUS:mask_polymorph_assembly (p1000)                            [100%] 1 of 1 ✔
[f1/af5e6c] process > CALL_STAPHYLOCOCCUS_AUREUS:mlst (p1000)                                               [100%] 1 of 1 ✔
[e3/18c716] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_create_batch_list                                [100%] 1 of 1 ✔
[9a/eaae63] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_allelecall (furious_allen)                       [100%] 1 of 1 ✔
[18/d2371c] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_split_results (p1000)                            [100%] 1 of 1 ✔
[aa/aef5a5] process > CALL_STAPHYLOCOCCUS_AUREUS:amrfinderplus (p1000)                                      [100%] 1 of 1 ✔
[62/029d58] process > CALL_STAPHYLOCOCCUS_AUREUS:resfinder (p1000)                                          [100%] 1 of 1 ✔
[52/ca8da3] process > CALL_STAPHYLOCOCCUS_AUREUS:virulencefinder (p1000)                                    [100%] 1 of 1 ✔
[0f/d1ca70] process > CALL_STAPHYLOCOCCUS_AUREUS:export_to_cdm (p1000)                                      [100%] 1 of 1 ✔
[76/8caee8] process > CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (p1000)                             [  0%] 0 of 1
executor >  local (21)
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:assembly_trim_clean                    -
[68/3d8766] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:save_analysis_metadata (furious_allen) [100%] 1 of 1 ✔
[ae/6f513b] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:skesa (p1000)                          [100%] 1 of 1 ✔
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:spades_illumina                        -
[-        ] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:spades_iontorrent                      -
[53/542a90] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:quast (p1000)                          [100%] 1 of 1 ✔
[87/f44b55] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:bwa_mem_ref (p1000)                    [100%] 1 of 1 ✔
[82/6a2913] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:samtools_index_ref (p1000)             [100%] 1 of 1 ✔
[af/e7cd30] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:post_align_qc (p1000)                  [100%] 1 of 1 ✔
[51/4e25c5] process > CALL_STAPHYLOCOCCUS_AUREUS:CALL_BACTERIAL_BASE:sourmash (p1000)                       [100%] 1 of 1 ✔
[b7/ccd15f] process > CALL_STAPHYLOCOCCUS_AUREUS:bwa_index (p1000)                                          [100%] 1 of 1 ✔
[11/e55e86] process > CALL_STAPHYLOCOCCUS_AUREUS:bwa_mem_dedup (p1000)                                      [100%] 1 of 1 ✔
[b6/7aa4b9] process > CALL_STAPHYLOCOCCUS_AUREUS:samtools_index_assembly (p1000)                            [100%] 1 of 1 ✔
[0e/a724ec] process > CALL_STAPHYLOCOCCUS_AUREUS:freebayes (p1000)                                          [100%] 1 of 1 ✔
[6f/62611d] process > CALL_STAPHYLOCOCCUS_AUREUS:mask_polymorph_assembly (p1000)                            [100%] 1 of 1 ✔
[f1/af5e6c] process > CALL_STAPHYLOCOCCUS_AUREUS:mlst (p1000)                                               [100%] 1 of 1 ✔
[e3/18c716] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_create_batch_list                                [100%] 1 of 1 ✔
[9a/eaae63] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_allelecall (furious_allen)                       [100%] 1 of 1 ✔
[18/d2371c] process > CALL_STAPHYLOCOCCUS_AUREUS:chewbbaca_split_results (p1000)                            [100%] 1 of 1 ✔
[aa/aef5a5] process > CALL_STAPHYLOCOCCUS_AUREUS:amrfinderplus (p1000)                                      [100%] 1 of 1 ✔
[62/029d58] process > CALL_STAPHYLOCOCCUS_AUREUS:resfinder (p1000)                                          [100%] 1 of 1 ✔
[52/ca8da3] process > CALL_STAPHYLOCOCCUS_AUREUS:virulencefinder (p1000)                                    [100%] 1 of 1 ✔
[0f/d1ca70] process > CALL_STAPHYLOCOCCUS_AUREUS:export_to_cdm (p1000)                                      [100%] 1 of 1 ✔
[76/8caee8] process > CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (p1000)                             [100%] 1 of 1, failed: 1 ✘
ERROR ~ Error executing process > 'CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (p1000)'

Caused by:
  Process `CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (p1000)` terminated with an error exit status (1)

Command executed:

  prp create-output \
    --sample-id p1000 \
    --amr /home/kast31/git/JASEN/work/aa/aef5a51330ecd33d9d351a50ae5207/p1000_amrfinder.out \
     \
    --cgmlst /home/kast31/git/JASEN/work/18/d2371c0add9c4d861b8bc49e5d2fd3/p1000_chewbbaca.out \
    --mlst /home/kast31/git/JASEN/work/f1/af5e6c01e835cf271e7a523f7fdd9a/p1000_mlst.json \
     \
    --quality /home/kast31/git/JASEN/work/af/e7cd30be0a494d042677e6239f51be/p1000_bwa.qc \
    --quast /home/kast31/git/JASEN/work/53/542a909df55007a90391289d972d41/p1000_quast.tsv \
    --resistance /home/kast31/git/JASEN/work/62/029d58c61cf03c16f164c88aac9734/p1000_resfinder.json --process-metadata /home/kast31/git/JASEN/work/62/029d58c61cf03c16f164c88aac9734/p1000_resfinder_meta.json \
    --run-metadata /home/kast31/git/JASEN/work/68/3d8766ad61e64417f1f0ffae903d25/p1000_analysis_meta.json \
     \
     \
    --virulence /home/kast31/git/JASEN/work/52/ca8da3b06b58ae569cf6d5fe69f6dd/p1000_virulencefinder.json --process-metadata /home/kast31/git/JASEN/work/52/ca8da3b06b58ae569cf6d5fe69f6dd/p1000_virulencefinder_meta.json \
    p1000_result.json

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
      return next(cls.discover(name=name))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  StopIteration
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/bin/prp", line 33, in <module>
      sys.exit(load_entry_point('prp', 'console_scripts', 'prp')())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/bin/prp", line 22, in importlib_load_entry_point
      for entry_point in distribution(dist_name).entry_points
                         ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
      return Distribution.from_name(distribution_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
      raise PackageNotFoundError(name)
  importlib.metadata.PackageNotFoundError: No package metadata was found for prp

Work dir:
  /home/kast31/git/JASEN/work/76/8caee8e9a4363a7633dcfb13383b7d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
 ```

**Comment by ryanjameskennedy** [comment]
After discussing this with @Emkago I think this is a problem with your OS. Please post the latest error as I believe it has change right?

**Comment by Emkago** [comment]
There was underlying problem with pip. After installing JASEN on another VM with the same system I was able to successfuly run the test run.

**Comment by ryanjameskennedy** [comment]
So problem is solved @Emkago?

**Comment by ryanjameskennedy** [comment]
I have confirmed on Slack with @Emkago that this is no longer a problem
