### ISSUE TITLE
Warning messages being written to some output files causing invalid JSON

### ISSUE THREAD

**Issue by samuell** [genomic-medicine-sweden/JASEN#226]
Got this error:

```bash
Got this error:

```bash
ERROR ~ Error executing process > 'CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (23ET101244)'

Caused by:
  Process `CALL_STAPHYLOCOCCUS_AUREUS:create_analysis_result (23ET101244)` terminated with an error exit status (1)

Command executed:

  prp create-output \
    --sample-id 23ET101244 \
    --amr /home/shl/tmp/nfwork/03/33bf81ce747c227d8bedad675d4f42/23ET101244_amrfinder.out \
    --kraken /home/shl/tmp/nfwork/ad/4247cac2648a9a71e29a63462f7a61/23ET101244_bracken.out \
    --cgmlst /home/shl/tmp/nfwork/76/a45a20a539b745edc97b3fe16f4a9a/23ET101244_chewbbaca.out \
    --mlst /home/shl/tmp/nfwork/69/34de2d0904e69ba161d98c40b2665a/23ET101244_mlst.json \
     \
    --quality /home/shl/tmp/nfwork/a4/31827c50f2bb86d22af6f0959312fb/23ET101244_bwa.qc \
    --quast /home/shl/tmp/nfwork/5f/922c0bf1f37ac6442f1fcfe131eba1/23ET101244_quast.tsv \
    --resistance /home/shl/tmp/nfwork/4d/b4ed64e0bef0c4a9becf217bbdcfd4/23ET101244_resfinder.json --process-metadata /home/shl/tmp/nfwork/4d/b4ed64e0bef0c4a9becf217bbdcfd4/23ET101244_resfinder_meta.json \
    --run-metadata /home/shl/tmp/nfwork/e1/f8448134cd1c5ce7f95cc8d256c956/23ET101244_analysis_meta.json \
     \
    --virulence /home/shl/tmp/nfwork/d5/4a6726799d341c01f2f67946523f36/23ET101244_virulencefinder.json --process-metadata /home/shl/tmp/nfwork/d5/4a6726799d341c01f2f67946523f36/23ET101244_virulencefinder_meta.json \
    23ET101244_result.json

Command exit status:
  1

Command output:
  (empty)

Command error:
  [2023-11-20 13:13:21,954] INFO in cli: Start generating pipeline result json
  [2023-11-20 13:13:21,955] INFO in cli: Parse quast results
  [2023-11-20 13:13:21,955] INFO in qc: Parsing tsv file: /home/shl/tmp/nfwork/5f/922c0bf1f37ac6442f1fcfe131eba1/23ET101244_quast.tsv
  [2023-11-20 13:13:21,955] INFO in cli: Parse quality results
  [2023-11-20 13:13:21,955] INFO in qc: Parsing json file: /home/shl/tmp/nfwork/a4/31827c50f2bb86d22af6f0959312fb/23ET101244_bwa.qc
  Traceback (most recent call last):
    File "/usr/local/bin/prp", line 33, in <module>
      sys.exit(load_entry_point('prp', 'console_scripts', 'prp')())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pipeline_result_processor/prp/cli.py", line 125, in create_output
      res: QcMethodIndex = parse_postalignqc_results(quality)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pipeline_result_processor/prp/parse/qc.py", line 49, in parse_postalignqc_results
      qc_dict = json.load(input_file)
                ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
      return loads(fp.read(),
             ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
      obj, end = self.scan_once(s, idx)
                 ^^^^^^^^^^^^^^^^^^^^^^
  json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 7 (char 6)

Work dir:
  /home/shl/tmp/nfwork/3e/56f1e5fb388b2361636311c7f147be

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

A closer investigation showed that the file `/home/shl/tmp/nfwork/a4/31827c50f2bb86d22af6f0959312fb/23ET101244_bwa.qc` contained not only JSON, but also a warning on line 1, causing the JSON to become invalid (which can also be checked by running the file via jq with `cat <thefile_bwa.qc> | jq`):

```json
[0.032s][warning][perf,memops] Cannot use file /tmp/hsperfdata_shl/70 because it is locked by another process (errno = 11)
{
   "tot_reads" : "11079699",
   "pct_above_x" : {
      "30" : 99.7698696674782,
      "500" : 44.8009643781353,
      "10" : 99.7783580813827,
      "250" : 99.4198404885554,
      "1000" : 0.0331873404738185,
      "100" : 99.7438738998957,
      "1" : 99.7858443908679
   },
   "dup_pct" : 0,
   "sample_id" : "23ET101244",
   "mean_cov" : 493.856753889049,
   "iqr_median" : 0.303092783505155,
   "ins_size" : "139",
   "ins_size_dev" : "98",
   "mapped_reads" : "10319327",
   "dup_reads" : "0"
}
```

Checking the workflow, it turns out this file is in turn produced by `/bin/postaln_qc.pl` in the repo. Not completely sure about where exactly this line is coming from though, but possibly / probably somewhere inside the `postaln_qc.pl` script I presume.

**Comment by samuell** [comment]
It seems this is a Java/JVM/JDK message (as seen e.g. [here](https://bugs.openjdk.org/browse/JDK-8298591)), which points to the Picard command executed from the postaln_qc.pl script, which runs on the JVM.

**Comment by ryanjameskennedy** [comment]
When we run `postaln_qc.pl ${bam} ${reference} ${sampleName} ${task.cpus} > ${output}` the stdout is being outputted as well with `>`. Instead we're gonna write it in python so the output is outputted by a function within `postaln_qc.py`.

**Comment by samuell** [comment]
> When we run `postaln_qc.pl ${bam} ${reference} ${sampleName} ${task.cpus} > ${output}` the stdout is being outputted as well with `>`. Instead we're gonna write it in python so the output is outputted by a function within `postaln_qc.py`.

Ah, yes of course... had been possible by taking the output as an argument to the `.pl` script as well I guess, but the python version should surely make it easier to keep updated in the future as well. Great stuff :+1:
