### ISSUE TITLE
Resfinder: KeyError: 'ampC-promoter'

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#231]
No idea what I've done here to cause this but I'm getting this error when I run ecoli samples that had previously worked before:
```
Command error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/site-packages/resfinder/__main__.py", line 5, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.8/site-packages/resfinder/run_resfinder.py", line 485, in main
      finder.write_results(
    File "/usr/local/lib/python3.8/site-packages/resfinder/cge/pointfinder.py", line 376, in write_results
      result_str = self.results_to_str(res_type=res_type,
    File "/usr/local/lib/python3.8/site-packages/resfinder/cge/pointfinder.py", line 323, in results_to_str
      str_tuple = self.mut2str(gene, gene_name, mis_matches,
    File "/usr/local/lib/python3.8/site-packages/resfinder/cge/pointfinder.py", line 1880, in mut2str
      gene_mut_name, resistence, pmid = self.look_up_known_muts(
    File "/usr/local/lib/python3.8/site-packages/resfinder/cge/pointfinder.py", line 2039, in look_up_known_muts
      if codon_pos in self.known_mutations[gene_ID][mut]:
  KeyError: 'ampC-promoter'
```

**Comment by ryanjameskennedy** [comment]
After creating an [issue](https://bitbucket.org/genomicepidemiology/resfinder/issues/124/keyerror-ampc-promoter) on Resfinder's bitbucket repo I found out that this error is due to the resfinder_db's and pointfinder_db's lack of backward compatibility with the resfinder software. As we are using resfinder version [4.1.11](https://depot.galaxyproject.org/singularity/resfinder%3A4.1.11--hdfd78af_0) (as it's the only singularity image in the [galaxy project](https://depot.galaxyproject.org/singularity/)). I have asked for an update on their singularity images so we'll see.
