### ISSUE TITLE
Adding stx to ecoli virulencefinder analysis breaks prp 

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/jasen#247]
When adding stx genes to the virulencefinder search the following error results from prp:
```
Traceback (most recent call last):
    File "/usr/local/bin/prp", line 8, in <module>
      sys.exit(cli())
               ^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/bonsai-prp/prp/cli.py", line 167, in create_bonsai_input
      vir: MethodIndex | None = parse_virulencefinder_vir_pred(virulencefinder)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/bonsai-prp/prp/parse/phenotype/virulencefinder.py", line 63, in parse_virulencefinder_vir_pred
      results: ElementTypeResult = _parse_virulencefinder_vir_results(pred)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/bonsai-prp/prp/parse/phenotype/virulencefinder.py", line 20, in _parse_virulencefinder_vir_results
      virulence_group = key.split("_")[1]
                        ~~~~~~~~~~~~~~^^^
  IndexError: list index out of range
```

**Comment by mhkc** [comment]
Fixed in version 0.3.0
