### ISSUE TITLE
Add information regarding sequencing run to output

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#82]
It would be nice if information regarding SE/PE and sequencing platform was added to the analysis_result.json output.

**Comment by ryanjameskennedy** [comment]
Related to #90

**Comment by ryanjameskennedy** [comment]
The following occurred after adding the respective information to `analysis_result.json`:
```
Error executing process > 'bacterial_default:create_analysis_result (test_sample_1)'

Caused by:
  Process `bacterial_default:create_analysis_result (test_sample_1)` terminated with an error exit status (1)

Command executed:

  prp create-output \
    --sample-id test_sample_1\
    --run-metadata test_sample_1_analysis_meta.json \
    --quast test_sample_1.quast.tsv \
    --kraken test_sample_1_bracken.out \
    --mlst test_sample_1.mlst.json \
    --cgmlst test_sample_1.chewbbaca \
    --virulence virulencefinder_test_sample_1.json --process-metadata virulencefinder_meta_test_sample_1.json \
    --resistance resfinder_test_sample_1.json --process-metadata resfinder_meta_test_sample_1.json \
    test_sample_1_result.json

Command exit status:
  1

Command output:
  (empty)

Command error:
  [2023-04-07 12:06:00,707] INFO in cli: Start generating pipeline result json
  Traceback (most recent call last):
    File "/usr/local/bin/prp", line 33, in <module>
      sys.exit(load_entry_point('prp', 'console_scripts', 'prp')())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pipeline_result_processor/prp/cli.py", line 78, in create_output
      run_info = RunInformation(**json.load(run_metadata))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
  pydantic.error_wrappers.ValidationError: 1 validation error for RunInformation
  run
    field required (type=value_error.missing)
```
